version: '3.7'
services:
    php:
        build: .docker/php
        container_name: usps-php
        volumes:
          - .:/home/wwwroot/usps-php
        networks:
          hostnet: {}
networks:
    hostnet:
        external: true
        name: sharednetwork
